### ISSUE TITLE
section-3-myshrall-shaylyn-smiley-face-svg

### ISSUE THREAD

**Issue by ShaylynHM** [ShaylynHM/svg-smiley-face#1]
@thatkidmadrid
@anna-pokhilenko
Did I enter the values incorrectly? My smiley is not turning yellow :(
![Screen Shot 2021-10-18 at 8 59 41 PM](https://user-images.githubusercontent.com/77545465/137827210-41878a7d-32b9-479a-8eef-d4d9883492ce.png)

**Comment by anna-pokhilenko** [comment]
I will take a look!

**Comment by anna-pokhilenko** [comment]
<img width="527" alt="Screen Shot 2021-10-18 at 9 16 32 PM" src="https://user-images.githubusercontent.com/55008926/137827889-22060848-47f3-4318-9ac8-61b373f59b3b.png">

Your css path had an extra / in there! 
Change it to what's on the screenshot, and it will turn yellow.)
